# Generated by Django 4.2.16 on 2024-11-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingevent_bookingprojection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
