exclude: .*/migrations/[0-9]+.*\.py$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.3
  hooks:
    - id: ruff
    - id: ruff-format
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
