services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: env/postgres.env
    volumes:
      - postgres_knyfe_data:/var/lib/postgresql/data
    secrets:
      - postgres_knyfe_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  knyfe:
    build:
      dockerfile: Dockerfile
    env_file: env/knyfe.env
    command: >
      sh -c "poetry install --no-interaction --no-ansi --no-root --no-cache &&
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./knyfe:/usr/src/app
      - .poetry/venv:/usr/src/app/.venv
      - .poetry/cache:/root/.cache/pypoetry
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

secrets:
  postgres_knyfe_password:
    file: ./env/postgres_knyfe_password

volumes:
  postgres_knyfe_data:
