[tool.poetry]
name = "knyfe"
version = "0.1.0"
description = ""
authors = ["Wanseo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
